version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "amogkam"
    ignore:
      - dependency-name: flake8
      - dependency-name: flake8-quotes
      - dependency-name: yapf
